imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: workflow.yml }
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
     

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOSUser Configuration
fos_user:
    db_driver:     orm
    firewall_name:  main
    user_class:     FIDUSTREAM\UserBundle\Entity\User
    from_email:
        address:        laurent.boucaud@fiducial.net
        sender_name:    lboucaud

#rabbitmq configuration
old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
    producers:
        workflow_transcoder:
            connection:       default
            exchange_options: {name: 'transcode_exchange', type: direct}
            queue_options:    {name: 'transcoding_queue'}
        resolution_transcoder:
            connection:       default
            exchange_options: {name: 'resolution_exchange', type: direct}
            queue_options:    {name: 'resolution_queue'}
    consumers:
        workflow_consumer:
            connection:       default
            exchange_options: {name: 'transcode_exchange', type: direct}
            queue_options:    
                name: 'confirmation_queue'
                routing_keys:      
                    - 'confirmation_queue'
            callback: "fidustream_video.workflow.workflow_consumer"
        
        resolution_consumer:
            connection:       default
            exchange_options: {name: 'resolution_exchange', type: direct}
            queue_options:    
                name: 'confirmationRes_queue'
                routing_keys:      
                    - 'confirmationRes_queue'
            callback: "fidustream_video.workflow.resolution_consumer"

    
