# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext #encodeur utilisé
        FIDUSTREAM\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_CONTRIBUTOR:   [ROLE_VIEWER]
        ROLE_MODERATOR:     [ROLE_VIEWER]
        ROLE_ADMIN:         [ROLE_CONTRIBUTOR, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username
            
      
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:    ^/login$
            anonymous:  true
            provider:   main
        main:
            pattern: ^/
            anonymous: false
            provider:   main
            # activate different ways to authenticate
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret: "%secret%"
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
        #access_control: ~
